var div1=document.createElement("div")
div1.className("header-container")
var h1=document.createElement("h1")
var h2=document.createElement("h2")
var h3=document.createElement("h3")
var h4=document.createElement("h4")
var h5=document.createElement("h5")
var h6=document.createElement("h6")
var h1text=document.createTextNode('This is an h1')
var h2text=document.createTextNode('This is an h2')
var h3text=document.createTextNode('This is an h3')
var h4text=document.createTextNode('This is an h4')
var h5text=document.createTextNode('This is an h5')
var h6text=document.createTextNode('This is an h6')